def intro
        puts ""
        puts ""
        puts ""
        puts "     NNNNNNNN        NNNNNNNN               AAA                  SSSSSSSSSSSSSSS                AAA"               
        puts "     N:::::::N       N::::::N              A:::A               SS:::::::::::::::S              A:::A"              
        puts "     N::::::::N      N::::::N             A:::::A             S:::::SSSSSS::::::S             A:::::A"             
        puts "     N:::::::::N     N::::::N            A:::::::A            S:::::S     SSSSSSS            A:::::::A"            
        puts "     N::::::::::N    N::::::N           A:::::::::A           S:::::S                       A:::::::::A"           
        puts "     N:::::::::::N   N::::::N          A:::::A:::::A          S:::::S                      A:::::A:::::A"          
        puts "     N:::::::N::::N  N::::::N         A:::::A A:::::A          S::::SSSS                  A:::::A A:::::A"         
        puts "     N::::::N N::::N N::::::N        A:::::A   A:::::A          SS::::::SSSSS            A:::::A   A:::::A"        
        puts "     N::::::N  N::::N:::::::N       A:::::A     A:::::A           SSS::::::::SS         A:::::A     A:::::A"       #<--This is so f$cking sick
        puts "     N::::::N   N:::::::::::N      A:::::AAAAAAAAA:::::A             SSSSSS::::S       A:::::AAAAAAAAA:::::A"      
        puts "     N::::::N    N::::::::::N     A:::::::::::::::::::::A                 S:::::S     A:::::::::::::::::::::A"     
        puts "     N::::::N     N:::::::::N    A:::::AAAAAAAAAAAAA:::::A                S:::::S    A:::::AAAAAAAAAAAAA:::::A"    
        puts "     N::::::N      N::::::::N   A:::::A             A:::::A   SSSSSSS     S:::::S   A:::::A             A:::::A"   
        puts "     N::::::N       N:::::::N  A:::::A               A:::::A  S::::::SSSSSS:::::S  A:::::A               A:::::A"  
        puts "     N::::::N        N::::::N A:::::A                 A:::::A S:::::::::::::::SS  A:::::A                 A:::::A" 
        puts "     NNNNNNNN         NNNNNNNAAAAAAA                   AAAAAAA SSSSSSSSSSSSSSS   AAAAAAA                   AAAAAAA"
        puts ""
        puts ""
        puts "              *****************************************************************************************"
        puts "              |  Welcome to the Comprehensive-ish List Interpreter for NASA's Exoplanetary Database!  |"
        puts "              |  Here you can browse known star systems and their exoplanets by distance from Earth.  |"
        puts "              *****************************************************************************************"
        puts ""
        sleep(0.25)
        puts "How many parsecs would you like to browse? "
        puts ""
end